# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '18_ProfileSerch' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'Moya'
  pod 'Moya-ObjectMapper'

end
